server:
  port: 9091
spring:
  application:
    name: user-edge-service
  redis:
    host: 192.168.122.152
    port: 6379
    timeout: 30000
thrift:
  userservice:
    ip: 127.0.0.1
    port: 7911
  messageservice:
    ip: 127.0.0.1
    port: 9090